# CUSTOMER PAGE VARIABLES (Separation of concerns)
nav_btn_customer                = '(//p[text()="Customers"])[2]'
customers_btn_create            = '//a[@aria-label="Create"]'

customers_created_email         = '//input[@name="email"]'
customers_txt_firstname         = '//input[@name="first_name"]'
customers_txt_lastname          = '//input[@name="last_name"]'
customers_txt_email             = '//input[@name="email"]'
customers_txt_birthday          = '//input[@name="birthday"]'
customers_txt_address           = '//textarea[@name="address"]'
customers_txt_city              = '//input[@name="city"]'
customers_txt_stateabbr         = '//input[@name="stateAbbr"]'
customers_txt_zipcode           = '//input[@name="zipcode"]'
customers_txt_password          = '//input[@name="password"]'
customers_txt_confirmpassword   = '//input[@name="confirm_password"]'
customers_btn_save              = '//button[normalize-space()="Save"]'

table_row                       = '//table//tbody//tr'
name_selector                   = '//table//tbody//tr[%s]//td[2]//a'
name_fallback_selector          = '//table//tbody//tr[%s]//td[2]//a//*[self::span or self::p][last()]'
last_seen_selector              = '//table//tbody//tr[%s]//td[3]'
orders_selector                 = '//table//tbody//tr[%s]//td[4]'
total_spent_selector            = '//table//tbody//tr[%s]//td[5]'
latest_purchase_selector        = '//table//tbody//tr[%s]//td[6]'
news_selector                   = '//table//tbody//tr[%s]//td[7]//*[name()="svg"]'
segment_selector                = '//table//tbody//tr[%s]//td[8]//span[contains(@class,"MuiChip-label")]'
